// Generated by CoffeeScript 1.7.1
(function() {
  var loadVideo, videoControls;

  loadVideo = (function() {
    function loadVideo(id, url) {
      var mpPatt, mpResult, oggPatt, oggResult, webmPatt, webmResult;
      this.id = id;
      this.url = url;
      oggPatt = new RegExp("\.og[gv]");
      oggResult = oggPatt.test(this.url);
      mpPatt = new RegExp("\.mp4");
      mpResult = mpPatt.test(this.url);
      webmPatt = new RegExp("\.webm");
      webmResult = webmPatt.test(this.url);
      if (oggResult) {
        $("#oggVid").attr({
          src: this.url
        });
        $("#" + this.id)[0].load();
      } else if (mpResult) {
        $("#mpVid").attr({
          src: this.url
        });
        $("#" + this.id)[0].load();
      } else if (webmResult) {
        $("#webmVid").attr({
          src: this.url
        });
        $("#" + this.id)[0].load();
      } else {
        alert("Error: Unknown Video Format!");
      }
    }

    return loadVideo;

  })();

  videoControls = (function() {
    function videoControls(id) {
      var divControl, playButton, restartButton, seekButton;
      this.id = id;
      divControl = $("<div id='video-controls' />");
      playButton = $("<button type='button' id='play_pause'>Play</button>");
      restartButton = $("<button type='button' id='restart'>Restart</button>");
      seekButton = $("<input type='range' id='seek_bar' value='0'>");
      divControl.append(playButton);
      divControl.append(restartButton);
      divControl.append(seekButton);
      $("#" + this.id).append(divControl);
    }

    videoControls.prototype.playPause = function(vidID) {
      this.vidID = vidID;
      if ($("#" + this.vidID)[0].paused) {
        $("#" + this.vidID)[0].play();
        return $("#play_pause").text("Pause");
      } else {
        $("#" + this.vidID)[0].pause();
        return $("#play_pause").text("Play");
      }
    };

    videoControls.prototype.restart = function(vidID) {
      this.vidID = vidID;
      return $("#" + this.vidID)[0].currentTime = 0;
    };

    videoControls.prototype.seek = function(vidID, time) {
      this.vidID = vidID;
      this.time = time;
      this.time = $("#" + this.vidID)[0].duration * this.time;
      return $("#" + this.vidID)[0].currentTime = this.time;
    };

    videoControls.prototype.updateSeekBar = function(vidID) {
      var time;
      this.vidID = vidID;
      time = (100 / $("#" + this.vidID)[0].duration) * $("#" + this.vidID)[0].currentTime;
      return $("#seek_bar").val(time);
    };

    videoControls.prototype.updateButton = function() {
      return $("#play_pause").text("Play");
    };

    return videoControls;

  })();

  $().ready(function() {
    var controls;
    $("#enter").click(function() {
      var url;
      url = $("#url").val();
      return new loadVideo("vidPlayer", url);
    });
    controls = new videoControls("divVideo");
    $("#play_pause").click(function() {
      return controls.playPause("vidPlayer");
    });
    $("#restart").click(function() {
      return controls.restart("vidPlayer");
    });
    $("#seek_bar").change(function() {
      var time;
      time = $("#seek_bar").val() / 100;
      return controls.seek("vidPlayer", time);
    });
    $("#vidPlayer").bind("timeupdate", function() {
      return controls.updateSeekBar("vidPlayer");
    });
    return $("#vidPlayer").bind("ended", function() {
      return controls.updateButton();
    });
  });

}).call(this);
