;;;;;;;;;;;;;
;PAREMETERS;;
;;;;;;;;;;;;;
(defparameter *game-over*  nil)
(defparameter *player-state-dead* nil)
(defparameter *reach-exit* nil)
(defparameter *Area* '((area-1 (Area-1. There is a dead body next to you.))
					   (area-2 (Area-2. There is a dead body next to you.))
					   (area-3 (There is a dead body next to you.))
					   (area-4 (There is a dead body next to you.))
					   (area-5 (There is a dead body next to you.))
					   (area-6 (There is a dead body next to you.))
					   (area-7 (There is a dead body next to you.))
					   (area-8 (There is a dead body next to you.))
					   (area-9 (There is a dead body next to you.))
					   (area-10 (There is a dead body next to you.))
					   (area-11 (There is a dead body next to you.))
					   (area-12 (There is a dead body next to you.))
					   (area-13 (There is a dead body next to you.))
					   (area-14 (There is a dead body next to you.))
					   (area-15 (There is a dead body next to you.))
					   (area-16 (There is a dead body next to you.))
					   (area-17 (There is a dead body next to you.))
					   (area-18 (There is a dead body next to you.))
					   (area-19 (There is a dead body next to you.))
					   (area-20 (There is a dead body next to you.))
					   (area-21 (There is a dead body next to you.))
					   (area-22 (There is a dead body next to you.))
					   (area-23 (There is a dead body next to you.))
					   (area-24 (There is a dead body next to you.))
					   (area-25 (There is a dead body next to you.))
					   (area-26 (There is a dead body next to you.))
					   (area-27 (There is a dead body next to you.))
					   (area-28 (There is a dead body next to you.))
					   (area-29 (There is a dead body next to you.))
					   (area-30 (There is a dead body next to you.))
					   (forge (You see an old forging stone. It looks like it could still be of use.))
					   (exit (You are Free!))))
				
;This is all the connections for the Areas in the dungeon
(defparameter *Paths* '((area-1 (area-2 east path)
							    (area-3 northeast path)
							    (area-4 south path))
						(area-2 (area-1 west exit)
							    (area-3 north exit)
							    (area-5 south exit)
								(area-6 east path))
						(area-3 (area-1 southwest exit)
							    (area-2 south exit)
								(area-7 northeast path))
						(area-4 (area-1 north exit)
							    (area-5 northeast exit))
						(area-5 (area-2 north exit)
								(area-4 southwest exit))
						(area-6 (area-2 west exit)
								(area-7 north exit)
								(area-25 south exit))
						(area-7 (area-6 south exit)
								(area-3 southwest path)
								(area-8 northwest exit)
								(area-9 east path))
						(area-8 (area-7 southeast path))
						(area-9 (area-7 west path)
								(area-10 east path))
						(area-10 (area-9 west path)
								 (area-11 east path)
								 (area-16 up ladder))
						(area-11 (area-10 west path)
								 (area-12 up ladder)
								 (area-6 southwest path))
						(area-12 (area-11 down ladder)
								 (area-14 northwest path)
								 (area-13 north path)
								 (area-15 northeast path)
								 (area-18 east path))
						(area-13 (area-12 southwest path)
								 (area-17 northeast path))
						(area-14 (area-12 southeast path)
								 (area-16 west path)
								 (area-15 north path))
						(area-15 (area-14 south path)
								 (area-12 east Long-path))
						(area-16 (area-10 down ladder)
								 (area-14 east path))
						(area-17 (area-13 southwest path))
						(area-18 (area-12 west path)
								 (area-19 east path))
						(area-19 (area-18 west path)
								 (area-21 south path)
								 (area-22 southeast path))
						(area-20 (area-18 southwest path)
								 (area-23 southeast path)
								 (area-28 east path))
						(area-21 (area-19 north path)
								 (area-22 east path)
								 (area-24 down ladder))
						(area-22 (area-21 west path)
								 (area-19 northwest path)
								 (area-23 east path))
						(area-23 (area-22 west path)
								 (area-20 northwest path)
								 (area-26 northeast path))
						(area-24 (area-21 up ladder)
								 (area-25 southwest path))
						(area-25 (area-6 west path)
								 (area-24 northeast path)
								 (forge south path))
						(area-26 (area-23 southwest path)
								 (area-27 east path))
						(area-27 (area-26 west path)
								 (area-28 north path))
						(area-28 (area-29 north path)
								 (area-27 south path)
								 (area-20 west path))
						(area-29 (exit east path))
								))
(defparameter *Visited-Area* '(area-1))
(defparameter *current-location* 'area-1)
 ;nil equals monster is alive, t equals monster is dead
(defparameter *Monster-location* '((area-2 (t))
								   (area-1 (t))
											))
(defparameter *items* '(sword))
(defparameter *items-location* '((sword area-1)))
								

								  