// Generated by CoffeeScript 1.7.1

/*
Makes a page with all the students' video quizzes
Copyright Jan Stelovsky UH ICS
MIT license, i.e. free to use even in the assignments or midterm makeup!
 */

(function() {
  $().ready(function() {
    var accounts, dom, sortAccounts, student, studentDiv, students, _i, _len, _results;
    dom = {
      container: $('#container')
    };
    if (localStorage.getItem("accounts") !== null) {
      console.log("From local storage");
      accounts = JSON.parse(localStorage.getItem("accounts"));
      students = null;
      sortAccounts = function() {
        var account, i, student, _i, _ref;
        for (account in accounts) {
          student = accounts[account];
          student.account = account;
          if (students == null) {
            students = [student];
          } else {
            for (i = _i = 0, _ref = students.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
              if (students[i].quizzes.length < student.quizzes.length) {
                students.splice(i, 0, student);
                student = null;
                break;
              }
            }
            if (student != null) {
              students.push(student);
            }
          }
        }
        return accounts;
      };
      sortAccounts();
      _results = [];
      for (_i = 0, _len = students.length; _i < _len; _i++) {
        student = students[_i];
        studentDiv = $('<div>').attr({
          id: student.account
        }).addClass('student').appendTo(dom.container);
        $('<h2>').addClass('name').html(student.name).appendTo(studentDiv);
        student.quizzes.reverse();
        _results.push($.each(student.quizzes, function(index, quiz) {
          var quizDiv;
          quizDiv = $('<div>').attr({
            id: "account_" + quiz.no
          }).addClass('quiz').appendTo(studentDiv);
          $('<p>').addClass('caption').html(quiz.caption).appendTo(quizDiv);
          $('<img>').attr({
            src: quiz.image,
            alt: quiz.yt_id
          }).appendTo(quizDiv);
          return quizDiv.click((function(_this) {
            return function() {
              var accObj, item, jsonString, quizObj;
              accObj = {};
              accObj["name"] = quizDiv.parent().children(".name").text();
              quizObj = [];
              item = {};
              item["no"] = quiz.no;
              item["game"] = quiz.game;
              item["image"] = quiz.image;
              item["caption"] = quiz.caption;
              item["url"] = quiz.url;
              item["yt_id"] = quiz.yt_id;
              quizObj.push(item);
              accObj["quizzes"] = quizObj;
              jsonString = JSON.stringify(accObj);
              return $("#accounts").val(jsonString);
            };
          })(this));
        }));
      }
      return _results;
    } else {
      console.log("From JSON FILE");
      return $.getJSON('accounts.json', function(accounts) {
        var jsonString, _j, _len1;
        students = null;
        sortAccounts = function() {
          var account, i, _j, _ref;
          for (account in accounts) {
            student = accounts[account];
            student.account = account;
            if (students == null) {
              students = [student];
            } else {
              for (i = _j = 0, _ref = students.length; 0 <= _ref ? _j < _ref : _j > _ref; i = 0 <= _ref ? ++_j : --_j) {
                if (students[i].quizzes.length < student.quizzes.length) {
                  students.splice(i, 0, student);
                  student = null;
                  break;
                }
              }
              if (student != null) {
                students.push(student);
              }
            }
          }
          return accounts;
        };
        sortAccounts();
        jsonString = JSON.stringify(accounts);
        localStorage.setItem("accounts", jsonString);
        for (_j = 0, _len1 = students.length; _j < _len1; _j++) {
          student = students[_j];
          studentDiv = $('<div>').attr({
            id: student.account
          }).addClass('student').appendTo(dom.container);
          $('<h2>').addClass('name').html(student.name).appendTo(studentDiv);
          student.quizzes.reverse();
          $.each(student.quizzes, function(index, quiz) {
            var quizDiv;
            quizDiv = $('<div>').attr({
              id: "account_" + quiz.no
            }).addClass('quiz').appendTo(studentDiv);
            $('<p>').addClass('caption').html(quiz.caption).appendTo(quizDiv);
            $('<img>').attr({
              src: quiz.image,
              alt: quiz.yt_id
            }).appendTo(quizDiv);
            return quizDiv.click((function(_this) {
              return function() {
                var accObj, item, quizObj;
                accObj = {};
                accObj["name"] = quizDiv.parent().children(".name").text();
                quizObj = [];
                item = {};
                item["no"] = quiz.no;
                item["game"] = quiz.game;
                item["image"] = quiz.image;
                item["caption"] = quiz.caption;
                item["url"] = quiz.url;
                item["yt_id"] = quiz.yt_id;
                quizObj.push(item);
                accObj["quizzes"] = quizObj;
                jsonString = JSON.stringify(accObj);
                return $("#accounts").val(jsonString);
              };
            })(this));
          });
        }
        return null;
      });
    }
  });


  /*
  coffee -cmw /Users/jan/Sites/315/video_quizzes/quizzes
   */

}).call(this);
